# Generated by Django 4.1.7 on 2023-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('job_number', models.CharField(max_length=250)),
                ('booking_codes', models.CharField(max_length=250, null=True)),
                ('booking_date', models.DateField()),
                ('time_tracked', models.DecimalField(decimal_places=1, max_digits=5)),
                ('task_estimate', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
        ),
    ]
