# Generated by Django 4.1.7 on 2023-03-16 19:05

from django.db import migrations, transaction
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeLogs', '0002_auto_20230316_2356'),
    ]

    # def update_data2(apps, schema_editor):
    #     TimeLogs = apps.get_model('TimeLogs', 'TimeLogs')
    #     for obj in TimeLogs.objects.all():
    #         if obj.time_tracked == 0:
    #             obj.time_tracked = None
    #             obj.save()
    #         if obj.task_estimate == 0:
    #             obj.task_estimate = None
    #             obj.save()
    
    # def update_data(apps, schema_editor):
    #     TimeLogs = apps.get_model('TimeLogs', 'TimeLogs')
    #     for obj in TimeLogs.objects.all():
    #         if obj.time_tracked == 0:
    #             obj.time_tracked = None
    #             obj.save()
    #         if obj.task_estimate == 0:
    #             obj.task_estimate = None
    #             obj.save()

    # def apply_migration(apps, schema_editor):
    #     with transaction.atomic():
    #         update_data(apps, schema_editor)

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='time_tracked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE TimeLogs_timelogs SET time_tracked = NULL WHERE time_tracked = 0;"),
        migrations.RunSQL("UPDATE TimeLogs_timelogs SET task_estimate = NULL WHERE task_estimate = 0;"),

    ]
